#!/usr/bin/env python
# -*- coding: utf-8 -*-
import tkinter as tk
from view import Chat


def main():
    root = tk.Tk()
    app = Chat(master=root)
    app.mainloop()

if __name__ == '__main__':
    main()
